name: Run Unit Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  py_build_tests:
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
  unit_tests:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/test_requirements.txt
      - name: Get Credential
        run: |
            mkdir -p ~/.local/share/neon
            echo $LIBRE_CREDS > ~/.local/share/neon/libre.json
        shell: bash
        env:
          AMAZON_CREDS: ${{secrets.amazon_creds}}
      - name: Test Language Detector
        run: |
          pytest tests/lang_detect_tests.py --doctest-modules --junitxml=tests/lang-detect-test-results.xml
      - name: Upload language detector test results
        uses: actions/upload-artifact@v4
        with:
          name: lang-detect-test-results-${{ matrix.python-version }}
          path: tests/lang-detect-test-results.xml
      - name: Test Language Translator
        run: |
          pytest tests/lang_translate_tests.py --doctest-modules --junitxml=tests/lang-translate-test-results.xml
      - name: Upload language translator test results
        uses: actions/upload-artifact@v4
        with:
          name: lang-translate-test-results-${{ matrix.python-version }}
          path: tests/lang-translate-test-results.xml
      - name: Test Language Transform
        run: |
          pytest tests/lang_transform_tests.py --doctest-modules --junitxml=tests/lang-transform-test-results.xml
      - name: Upload language transformation test results
        uses: actions/upload-artifact@v4
        with:
          name: lang-transform-test-results-${{ matrix.python-version }}
          path: tests/lang-transform-test-results.xml
